// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sender.API.Database;

namespace Sender.API.Migrations
{
    [DbContext(typeof(SenderDbContext))]
    partial class SenderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Sender.API.Models.ReceiverEmailModel", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Guid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Email");

                    b.Property<Guid>("GroupGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("GroupGuid");

                    b.HasKey("Guid")
                        .HasName("PK_Email");

                    b.HasIndex("GroupGuid")
                        .HasDatabaseName("IDX_Email_GroupGuid");

                    b.ToTable("Emails");
                });
#pragma warning restore 612, 618
        }
    }
}
