version: "3"

services:
  downloader-db:
    container_name: rss-service-downloader-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: unhackable_password
      POSTGRES_USER: kvp
      POSTGRES_DB: downloader-db

  filter-db:
    container_name: rss-service-filter-db
    image: postgres
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: unhackable_password
      POSTGRES_USER: kvp
      POSTGRES_DB: filter-db

  sender-db:
    container_name: rss-service-sender-db
    image: postgres
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: unhackable_password
      POSTGRES_USER: kvp
      POSTGRES_DB: sender-db

  manager-db:
    container_name: rss-service-manager-db
    image: postgres
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: unhackable_password
      POSTGRES_USER: kvp
      POSTGRES_DB: manager-db

  bus:
    container_name: rss-service-bus
    image: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

  email-server:
    container_name: rss-service-email
    image: rodolpheche/wiremock:2.27.2
    ports:
      - "6363:8080"
