// <auto-generated />
using System;
using Filter.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Filter.API.Migrations
{
    [DbContext(typeof(FilterDbContext))]
    [Migration("20211109212228_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Filter.API.Models.FilterModel", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Guid");

                    b.Property<string>("Filter")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Filter");

                    b.Property<Guid>("GroupGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("GroupGuid");

                    b.HasKey("Guid")
                        .HasName("PK_Filter");

                    b.HasIndex("GroupGuid")
                        .HasDatabaseName("IDX_Filter_GroupGuid");

                    b.ToTable("Filters");
                });
#pragma warning restore 612, 618
        }
    }
}
